<!-- AUTO-GENERATED BY TEAM HARNESS v{{ harness_version }} -->
<!-- DO NOT EDIT DIRECTLY — run ./scripts/harness render to regenerate -->

# 项目信息

项目名称：{{ project_name }}{% if project_description %}
项目简介：{{ project_description }}{% endif %}
Java 版本：{{ java_version }}
构建工具：Maven{% if enabled_profiles %}
启用的 Profile：{{ enabled_profiles }}{% endif %}

# 核心规则

1. 不得编造不存在的接口、类或配置。
2. 仅修改完成当前任务所需的最小范围。
3. 不得修改生产配置或写入敏感信息。
4. 修改后执行相关编译和测试。
5. 高风险操作必须人工确认。

# 常用命令

```bash
{{ compile_command }}
{{ test_command }}
{{ package_command }}
```

# 规则索引

{% for entry in rule_index %}
- {{ entry.name }}：{{ entry.path }}
{% endfor %}

- 项目本地规则：{{ local_rules_index }}

# 按需加载

执行任务前，根据任务类型和变更文件，使用 `./scripts/harness rules select` 选择相关规则。
禁止默认读取完整规则库。

- 常驻上下文目标：≤ {{ context_max_tokens }} Token
- 常驻上下文最大文件数：{{ context_max_files }}
- 任务规则预算：≤ {{ task_max_tokens }} Token / {{ task_max_files }} 文件
- 代码审查预算：≤ {{ review_max_tokens }} Token / {{ review_max_rules }} 规则

# 项目本地说明

{% if has_local_readme %}
参见 {{ local_rules_main }}
{% else %}
暂无项目本地说明文件。使用 `./scripts/harness init` 初始化。
{% endif %}
