<!-- AUTO-GENERATED BY TEAM HARNESS v{{ harness_version }} -->
<!-- DO NOT EDIT DIRECTLY -->

# {{ profile_name }} 规则索引

> Profile 版本: {{ profile_version }}
> 描述: {{ profile_description }}

## 规则列表

| 规则 ID | 严重级别 | 标题 | 触发条件 | 文件 |
|---------|---------|------|---------|------|
{% for rule in rules %}
| {{ rule.id }} | {{ rule.severity }} | {{ rule.title }} | {{ rule.triggers | join(', ') }} | {{ rule.path }} |
{% endfor %}

## 快速查找

- 修改 Controller → 查看 Controller 规则
- 修改 Consumer → 查看 Consumer 规则
- 修改测试 → 查看 Testing 规则
- 新增日志 → 查看 Logging 规则
- 新增异常 → 查看 Exception 规则
